---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook -vvvv tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
