---
- name: install python dependencies
  become: yes
  pip:
    name: "{{ item }}"
  with_items:
    - docker-py
    - netaddr

- name: setup interfaces
  become: yes
  template:
    src: interfaces
    dest: /etc/network/interfaces.d/dockerdns
  register: interfaces

- name: start interface
  when: interfaces|changed
  become: yes
  command: ifup {{ iface }}

- name: setup .docker zone delegation
  become: yes
  template:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.d/docker.conf
  register: dnsmasq_docker_conf

- name: create dnsmasq.service.d
  become: yes
  file:
    state: directory
    path: /etc/systemd/system/dnsmasq.service.d/

- name: reorder dnsmasq boot dependencies
  become: yes
  copy:
    dest: /etc/systemd/system/dnsmasq.service.d/dockerdns.conf
    content: |
      [Unit]
      Wants=network-online.target
      After=network-online.target

- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: restart dnsmasq
  when: dnsmasq_docker_conf|changed
  become: yes
  service:
    name: dnsmasq
    state: restarted

- name: restart docker
  when: dnsmasq_docker_conf|changed
  become: yes
  shell: systemctl restart docker

- name: run dnsdock
  become: yes
  docker:
    name: dnsdock
    image: tonistiigi/dnsdock
    docker_api_version: "1.20"
    expose: [53/udp]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "{{ network|ipaddr('2')|ipaddr('address') }}:53:53/udp"
    restart_policy: always
    command: -domain={{ domain }}

- name: test resolution
  shell: getent hosts dnsdock.docker
  changed_when: false
